# Use Dockerized infrastructure
sudo: false
language: node

before_install:
- echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
- sudo apt-get update -qq
- sudo apt-get install google-cloud-sdk

script:
# Run the unit tests
- python test_main.py
# [START deploy]
# Deploy the app
# - gcloud -q preview app deploy app.yaml --promote
# Run and end to end test
# - python e2e_test.py
# [END deploy]