# Use Dockerized infrastructure
sudo: false
language: node

before_install:
- sudo curl https://sdk.cloud.google.com | /tmp/gcloud-install.sh; bash /tmp/gcloud-install.sh --disable-prompts --install-dir=/tmp
- sudo ls -l /tmp

script:
# Run the unit tests
- python test_main.py
# [START deploy]
# Deploy the app
# - gcloud -q preview app deploy app.yaml --promote
# Run and end to end test
# - python e2e_test.py
# [END deploy]